### ISSUE TITLE
ImportError: cannot import name 'Self' from 'typing' (unknown location)

### ISSUE THREAD

**Issue by aleksejrs** [lune-stone/anki-addon-limit-new-by-young#22]
```
Anki 24.04.2 (a1fa865b)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.7.12-amd64-x86_64-with-glibc2.38

When loading Limit New by Young:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/home/anki/.local/share/Anki2/addons21/214963846/__init__.py", line 14, in <module>
    from .anki_api import AnkiApi as Anki
  File "/home/anki/.local/share/Anki2/addons21/214963846/anki_api.py", line 3, in <module>
    from typing import TYPE_CHECKING, Any, Callable, Self, Sequence
```

**Comment by lune-stone** [comment]
Based on [this](https://stackoverflow.com/questions/77247446/cannot-import-name-self-from-typing) stackoverflow, this happens because typing.Self was added in Python 3.11. It suggests that it might be possible to work around the issue by using `from typing_extensions import Self` as an alternative. Are you able to confirm that?

Otherwise removing `Self` from the file should work.

**Comment by aleksejrs** [comment]
```
    from typing_extensions import Self
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by lune-stone** [comment]
Maybe this will work?

```
from typing import NewType, Any

try:
	from typing import Self
except:
	Self = NewType('Self', Any)
```

**Comment by aleksejrs** [comment]
Seems to work. Although there was no error after just removing "Self" (I haven't run the tests).
